name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml
  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - run: pnpm install
      - run: pnpm build
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "*.vsix"
          token: ${{ secrets.GITHUB_TOKEN }}
